name = Homepage
description = Social Finance homepage layout with a prominent hero region.
preview = preview.png
template = homepage-layout

; Regions
regions[navigation]     = Navigation bar
regions[hero]           = Hero
regions[content]       	= Content
regions[whoweare]       = Who we are
regions[search]         = Search
regions[whatwedo]       = What we do
regions[resources]      = Resources
regions[careers]        = Careers
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/homepage/homepage.layout.css
stylesheets[all][] = css/layouts/homepage/homepage.layout.no-query.css
