name = User profile
description = Social Finance page layout for user profiles.
preview = preview.png
template = user-layout

; Regions
regions[navigation]     = Navigation bar
regions[title]           = Title
regions[content]       	= Content
regions[sidebar]	    = Sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/user/user.layout.css
stylesheets[all][] = css/layouts/user/user.layout.no-query.css
