name = Section
description = Social Finance page layout for section landing pages
preview = preview.png
template = section-layout

; Regions
regions[navigation]     = Navigation bar
regions[hero]           = Hero
regions[content]       	= Content
regions[sidebar]  = Sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/section/section.layout.css
stylesheets[all][] = css/layouts/section/section.layout.no-query.css
