name = Blog landing page
description = 2-column landing page layout for the Blog section.
preview = preview.png
template = bloglanding-layout

; Regions
regions[navigation]     = Navigation bar
regions[hero]           = Hero
regions[content]       	= Content
regions[leftcol]  		= Left column
regions[rightcol]       = Right column
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/bloglanding/bloglanding.layout.css
stylesheets[all][] = css/layouts/bloglanding/bloglanding.layout.no-query.css