name = What we do page
description = Layout page layout for the What we do section.
preview = preview.png
template = wwd-layout

; Regions
regions[navigation]     = Navigation bar
regions[hero]           = Hero
regions[content]       	= Content
regions[leftcol]  		= Left column
regions[rightcol]       = Right column
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/wwd/wwd.layout.css
stylesheets[all][] = css/layouts/wwd/wwd.layout.no-query.css
