name = What we do landing page
description = Landing page layout for the What we do section.
preview = preview.png
template = wwdlanding-layout

; Regions
regions[navigation]     = Navigation bar
regions[hero]           = Hero
regions[content]       	= Content
regions[publicservice]  = Better Public Services
regions[charities]      = Charities and Social Enterprises
regions[trusts]         = Trusts and foundations
regions[international]  = International work
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/wwdlanding/wwdlanding.layout.css
stylesheets[all][] = css/layouts/wwdlanding/wwdlanding.layout.no-query.css