name = Projects
description = Social Finance page layout for project pages.
preview = preview.png
template = projects-layout

; Regions
regions[navigation]     = Navigation bar
regions[hero]           = Hero
regions[content]       	= Content
regions[sidebar]	    = Sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/projects/projects.layout.css
stylesheets[all][] = css/layouts/projects/projects.layout.no-query.css
