name = Subpage
description = Social Finance page layout for all information pages.
preview = preview.png
template = subpage-layout

; Regions
regions[navigation]     = Navigation bar
regions[hero]           = Hero
regions[content]       	= Content
regions[sidebar-first]  = Sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/subpage/subpage.layout.css
stylesheets[all][] = css/layouts/subpage/subpage.layout.no-query.css
